In [1]:
import numpy as np
import pandas as pd

In [2]:
medical_train = pd.read_csv('brain_cancer_samples.csv')
medical_test = pd.read_csv('brain_cancer_test.csv')

In [3]:
medical_train.describe()

Patient ID     2D Surface  Contour Size  Total Surface     Density  \
count  145.000000     145.000000    145.000000     145.000000  145.000000   
mean    73.000000   11197.331034    561.902852   24948.872414    0.616912   
std     42.001984   37505.105580    700.870894   61834.821186    0.306082   
min      1.000000      10.000000     13.071068      12.000000    0.055568   
25%     37.000000     395.000000    120.124890     693.000000    0.414042   
50%     73.000000    1437.500000    275.622365    2979.500000    0.674065   
75%    109.000000    5446.500000    743.737149   13503.500000    0.888472   
max    145.000000  386972.500000   3924.688712  491608.500000    0.997361   

         Diameter  Primary Axis  Shape Variation    Location  \
count  145.000000    145.000000       145.000000  145.000000   
mean    74.180916    130.089811       203.119272    1.524138   
std     93.887532    181.937427       395.821280    1.333764   
min      3.568248      2.107625         4.760943    0.000000   
25%     22.426092     20.596636        45.993591    0.000000   
50%     42.781793     56.513119        91.704414    1.000000   
75%     83.274841    209.590240       283.598083    3.000000   
max    701.932112   1388.291992      4315.014648    4.000000   

       Eccentricity_Real  Eccentricity_Imag       Class  
count       1.450000e+02         145.000000  145.000000  
mean        1.112586e-16           1.817069    0.800000  
std         1.671465e-16           2.733265    0.641179  
min         1.270000e-17           0.206967    0.000000  
25%         4.980000e-17           0.812745    0.000000  
50%         6.940000e-17           1.133157    1.000000  
75%         1.090000e-16           1.772417    1.000000  
max         1.720000e-15          28.144217    2.000000

In [4]:
medical_train.head(10)

Patient ID  2D Surface  Contour Size  Total Surface   Density    Diameter  \
0           1      1325.5    160.124890         1518.5  0.872901   41.081371   
1           2        81.5     39.556349           88.0  0.926136   10.186708   
2           3     57177.0    912.607209        57611.0  0.992467  269.814784   
3           4       135.0     92.083260          206.0  0.655340   13.110581   
4           5      6653.0   1525.307779        84025.5  0.079178   92.037290   
5           6       101.0     62.284271          173.0  0.583815   11.340070   
6           7        11.5     13.071068           12.0  0.958333    3.826520   
7           8       104.5     42.727922          109.0  0.958716   11.534883   
8           9      1306.0    208.024384         1944.5  0.671638   40.778068   
9          10      2062.5   1125.050858        37117.0  0.055568   51.245064   

   Primary Axis  Shape Variation  Location  Eccentricity_Real  \
0     36.290924        53.992371         2       6.750000e-17   
1      8.801125        15.591203         2       8.950000e-17   
2    234.644165       312.589264         4       5.390000e-17   
3      6.568726        40.183521         3       3.700000e-16   
4    383.980133       402.407623         3       1.920000e-17   
5     14.772180        24.742086         0       8.230000e-17   
6      3.650945         4.760943         4       5.120000e-17   
7      9.347109        16.334406         1       8.780000e-17   
8     43.150715        54.268845         1       4.670000e-17   
9    543.773193       940.586609         2       8.640000e-17   

   Eccentricity_Imag  Class  
0           1.101565      1  
1           1.462264      1  
2           0.880179      0  
3           6.035112      0  
4           0.313504      1  
5           1.343625      0  
6           0.836956      1  
7           1.433137      2  
8           0.762695      1  
9           1.411383      0

In [5]:
medical_test.shape

(60, 12)

In [6]:
medical_train.columns

Index(['Patient ID', '2D Surface', 'Contour Size', 'Total Surface', 'Density',
       'Diameter', 'Primary Axis', 'Shape Variation', 'Location',
       'Eccentricity_Real', 'Eccentricity_Imag', 'Class'],
      dtype='object')

In [7]:
target_column = 'Class'

In [8]:
y_train, X_train = medical_train[target_column], medical_train.drop(columns=[target_column],inplace=False)

y_test, X_test = medical_test[target_column], medical_test.drop(columns=[target_column],inplace=False)

In [9]:
def logistic(z):
    return 1. / (1. + np.exp(-z))

In [10]:
logistic(np.array([0,1,2]))

print()

In [11]:
def predict_log(X, beta, beta0):
    X_ = np.hstack((np.ones((X.shape[0], 1)), X))
    beta_ = np.insert(beta, 0, beta0)
    y_log = logistic(X_ @ beta_)
    return y_log

In [12]:
# predict_log(X_train, np.array([1,2,3,4,5,6,7,8,9,10,11]),5)
predict_log(X_train, np.array([3.00000000e-02, 2.20310345e+00, 1.10803414e+03, 2.67910233e+01,
 1.60119707e+03, 2.42090793e-02, 4.98400234e+00, 5.68353679e+00,
 8.71214793e+00, 6.31034483e-02, 2.79534483e-18]), 0.04567474893000001)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
predict_log(X_train, np.zeros(11),0)

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5])

In [14]:
def propagate(X, y, beta, beta0, lam):
    """
    Arguments:
    X: Data of shape (N, p)
    y: True label vector of size N
    beta: Parameter vector, a numpy array of size p
    beta0: 
    lam: 

    Returns:
    grads: 
    mean_loss: Mean sample loss for the negative log-likelihood

    """
    y_log = predict_log(X, beta, beta0)

    # Mean sample loss function
    mean_loss = -np.mean(y*np.log(y_log) + (1-y)*np.log(1-y_log)) + (lam/2) * np.linalg.norm(beta)**2
    
    # Derivatives
    dbeta = np.mean(X.T * (y_log - y), axis=1) + lam*beta 
    dbeta0 = np.mean(y_log - y)
    
    mean_loss = np.squeeze(mean_loss)
  
    # Store gradients in a dictionary
    grads = {'dbeta': dbeta, 'dbeta0' : dbeta0}
  
    return grads, mean_loss

In [15]:
def optimise(X, y, beta, beta0, lam=0.0025, num_iterations=1000, learning_rate=0.1, print_loss=False):
    """
    Arguments:
    X: Data of shape (N, p+1)
    y: True label vector of size N
    beta: Parameter vector, a numpy array of size p
    beta0:
    lam0:
    num_iterations: Number of iterations
    learning_rate: Step size in updating procedure
    print_loss: 'True' to print the mean loss every 100 iterations

    Returns:
    params: Dictionary containing the parameter vector beta and parameter beta0
    grads: Dictionary containing the gradient
    mean_loss_history: List of all the mean loss values computed during the optimisation (can be used to plot the learning curve)

    """
    mean_loss_history = []
    
    for i in range(num_iterations):
        
        # Calculating the loss and gradients
        grads, mean_loss = propagate(X, y, beta, beta0, lam)
      
        # Retrieving derivatives from grads
        dbeta = grads['dbeta']
        dbeta0 = grads['dbeta0']
        
        # Updating procedure
        beta -= learning_rate * dbeta
        beta0 -= learning_rate * dbeta0#
    
              
        # Record the loss values
        if i % 100 == 0:
            mean_loss_history.append(mean_loss)
      
        # Printing the loss every 100 iterations
        if print_loss and i % 1 == 0:
            print ('Mean loss after iteration %i: %f' %(i, mean_loss))
  
    # Saving parameters and gradients in dictionary
    params = {'beta': beta, 'beta0' : beta0}
    grads = {'dbeta': dbeta, 'dbeta0': dbeta0}
  
    return params, grads, mean_loss_history

In [16]:
def predict(X_test, beta, beta0):
    """
    Arguments:
    X_test: Test set of shape (N_test, p)
    beta: Parameter vector, a numpy array of size p
    beta0:

    Returns:
    y_pred: Vector containing all binary predictions (0/1) for X_test
    
    """
    N_test = X_test.shape[0]
#     y_pred = np.zeros((N_test, 1))
#     beta = beta.reshape(X_test.shape[1], 1)
  
    # Predicting the probabilities
    y_log = predict_log(X_test, beta, beta0)
  
    y_pred = y_log.round()
  
    return y_pred

In [17]:
def model(X_train, y_train, X_test, y_test, lam=0.0025, num_iterations=2000, learning_rate=0.1, print_loss=False):
    # Initialising parameters with zeros
    beta, beta0 = np.zeros(X_train.shape[1]), 0

    # Gradient descent
    parameters, grads, mean_loss_history = optimise(X_train, y_train, beta, beta0, lam, num_iterations, learning_rate, print_loss=print_loss)

    # Retrieving parameter vector beta from dictionary 'parameters'
    beta = parameters['beta']
    beta0 = parameters['beta0']

    # Predicting test and training set examples
    y_pred_test = predict(X_test, beta, beta0)
    y_pred_train = predict(X_train, beta, beta0)

    # Printing train/test accuracy
    print('Training accuracy: {} %'.format(100 - np.mean(np.abs(y_pred_train - y_train)) * 100))
    print('Test accuracy: {} %'.format(100 - np.mean(np.abs(y_pred_test - y_test)) * 100))

    # Saving all the information
    d = {'mean_loss_history': mean_loss_history, 'y_pred_test': y_pred_test, 'y_pred_train': y_pred_train, 'beta': beta, 'learning_rate': learning_rate, 'num_iterations': num_iterations}
  
    return d

In [18]:
d = model(X_train.to_numpy(), y_train.to_numpy(), X_test.to_numpy(), y_test.to_numpy(), num_iterations=10, print_loss=True)

Mean loss after iteration 0: 0.693147
Mean loss after iteration 1: nan
Mean loss after iteration 2: nan
Mean loss after iteration 3: nan
Mean loss after iteration 4: nan
Mean loss after iteration 5: nan
Mean loss after iteration 6: nan
Mean loss after iteration 7: nan
Mean loss after iteration 8: nan
Mean loss after iteration 9: nan
Training accuracy: 55.172413793103445 %
Test accuracy: 58.33333333333333 %


<ipython-input-14-9cbd878f45c7>:18: RuntimeWarning: divide by zero encountered in log
  mean_loss = -np.mean(y*np.log(y_log) + (1-y)*np.log(1-y_log)) + (lam/2) * np.linalg.norm(beta)**2
<ipython-input-14-9cbd878f45c7>:18: RuntimeWarning: invalid value encountered in multiply
  mean_loss = -np.mean(y*np.log(y_log) + (1-y)*np.log(1-y_log)) + (lam/2) * np.linalg.norm(beta)**2
C:\Users\phily\anaconda3\lib\site-packages\numpy\core\_methods.py:178: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)


In [19]:
# X = X_train.to_numpy()
Xab = np.array([[1,2],[3,4],[5,6]])
yab = np.array([6,7,8])

Xab.T * yab

array([[ 6, 21, 40],
       [12, 28, 48]])

In [20]:
np.mean(Xab.T * yab, axis=1)

array([22.33333333, 29.33333333])

In [21]:
(Xab.T @ yab)/Xab.shape[0]

array([22.33333333, 29.33333333])